title: Omkar Kurve
logo: /assets/img/logo.png
description:   <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href= "www.linkedin.com/in/omkar-kurve">LinkedIn</a> |
  <a href="https://github.com/omkarkurve">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
