title: Omkar Kurve
logo: /assets/img/IMG_20211124_161125.jpg
description:   <p align="center">
  <a href= "https://www.linkedin.com/in/omkar-kurve"> LinkedIn</a> |
  <a href="https://github.com/omkarkurve">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
